# Advanced Intelligent Web Crawler & AI Penetration Tester Configuration
# Production-grade configuration file

# AI Configuration
ai:
  # Primary AI provider: "groq", "gemini", "openai", "anthropic"
  provider: "groq"
  
  # Provider-specific configurations
  groq:
    model: "llama-3.1-8b-instant"
    api_key: "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"
    fallback_models: ["llama3-8b-8192", "gemma-7b-it", "llama3-groq-8b-8192-tool-use-preview"]
  
  gemini:
    model: "gemini-2.0-flash-exp"
    api_key_env: "GOOGLE_API_KEY"  # Set this environment variable
    # api_key: "your_gemini_api_key_here"  # Or set directly
  
  openai:
    model: "gpt-4"
    api_key_env: "OPENAI_API_KEY"
    # api_key: "your_openai_api_key_here"
  
  anthropic:
    model: "claude-3-sonnet-20240229"
    api_key_env: "ANTHROPIC_API_KEY"
    # api_key: "your_anthropic_api_key_here"
  
  # General settings
  max_retries: 3
  timeout: 30
  context_window: 2000

# Browser Configuration
browser:
  headless: false
  stealth_mode: true
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  window_size: "1920x1080"
  page_load_timeout: 30
  implicit_wait: 10
  chrome_options:
    - "--disable-blink-features=AutomationControlled"
    - "--disable-web-security"
    - "--disable-features=VizDisplayCompositor"
    - "--disable-dev-shm-usage"
    - "--no-sandbox"
    - "--disable-gpu"
    - "--disable-extensions"
    - "--disable-plugins"

# Real-time Monitoring Configuration
monitoring:
  interval: 2
  dom_monitoring: true
  console_monitoring: true
  network_monitoring: true
  max_dom_size: 2000
  max_console_entries: 100
  max_network_events: 50

# Logging Configuration
logging:
  level: "INFO"
  file_enabled: true
  file_path: "logs/crawler.log"
  json_format: true
  max_file_size: "10MB"
  backup_count: 5
  console_output: true
  structured_logging: true

# Security Testing Configuration
security:
  max_payloads_per_type: 10
  test_timeout: 10
  retry_failed_tests: true
  max_retries: 3
  vulnerability_threshold: 5
  risk_scoring:
    critical: 9
    high: 7
    medium: 5
    low: 3
    info: 1

# Network Configuration
network:
  request_timeout: 30
  max_redirects: 5
  retry_strategy:
    total: 3
    backoff_factor: 0.3
    status_forcelist: [429, 500, 502, 503, 504]

# Performance Configuration
performance:
  max_concurrent_requests: 5
  rate_limit: 1.0  # requests per second
  memory_limit: "2GB"
  cpu_limit: 80  # percentage

# Output Configuration
output:
  save_screenshots: false
  screenshot_path: "screenshots/"
  save_reports: true
  report_format: "json"
  report_path: "reports/"
  include_ai_analysis: true
  include_technical_details: true

# Privacy & Security
privacy:
  sanitize_logs: true
  mask_sensitive_data: true
  sensitive_patterns:
    - "password"
    - "api_key"
    - "token"
    - "secret"
  exclude_domains: []
  respect_robots_txt: true

# Advanced Features
advanced:
  enable_ai_analysis: true
  enable_visual_analysis: false
  enable_behavioral_analysis: true
  enable_threat_intelligence: false
  enable_machine_learning: false
  custom_payloads_file: null
  custom_headers_file: null 